<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
$isfirst=0;
$isfirstnav=0;
?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
            <legend id="customizeTitle" class="legend title">
                <span><?= /* @escapeNotVerified */ __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend><br />
            <!--<?= $block->getChildHtml('product_info_bundle_options_top') ?>-->
            <div class="thelegend defaultcomposiciones">¿Qué trae esta composición?</div>
            <div class="opcionesDefault defaultcomposicionesopciones">
                <?php foreach ($options as $option): 

                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

                    $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 

                    $itemsincart = $cart->getQuote()->getAllItems();

                    $allitmesku=array();
                    foreach ($itemsincart as $mitem) {
                        $skuopcion = explode('-',$mitem->getSku());
                        foreach ($skuopcion as $sku) {
                            $allitmesku[]=$sku;
                        }
                    }

                    $_option = $block->getOption();
                    $_selections  = $option->getSelections();
                    foreach ($_selections as $_selection):
                        /*echo "<hr/>" . $_selection->getSku()."<hr/>";
                        echo in_array($_selection->getSku(), $allitmesku);
                        var_dump($allitmesku);
                        echo in_array($_selection->getSku(), $allitmesku);*/
                           ?>
                            <div class="field choice col-md-3 <?php 
                            if(/*$_selection->getIsDefault()==1 && 
                            */in_array($_selection->getSku(), $allitmesku))
                            { 
                                echo 'likedir';
                            }else{ 
                                echo 'dontlikedit'; 
                            } 
                        ?> familia<?php echo $option->getId(); ?>" id="selectedoption<?php echo $_selection->getId(); ?>">
                              <div class="choice--item">
                                <div class="bundle--imagechoice">
                                  <img src="<?php 
                                            $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($_selection->getId());
                                            $productImageUrl = substr($block->getBaseUrl(),0,-3).'pub/media/catalog/product'.$_product->getImage();
                                            echo $productImageUrl;
                                         ?>">
                                </div>
                                <div class="bundle--moreinfo--parent">
                                    <div class="bundle--moreinfo">
                                      <?php echo __('More information') ?>
                                    </div>
                                    <div class="bundle--moreinfo--description">
                                        <div class="closeinfo">X</div><?php echo $_product->getDescription(); ?>
                                    </div>
                                </div>
                                
                                <div class="bundle__option--info">
                                  <label class="label">
                                    <span style="display: none;"><?php echo $_selection->getName(); ?></span>
                                    <div class="bundle__option--title">
                                      <?php echo $_selection->getName(); ?>
                                      
                                    </div>
                                    <div class="bundle__option--price">
                                      <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
                                      $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                                      $price =  $_selection->getPrice('final_price');
                                      $formattedPrice = $priceHelper->currency($price, true, false); 
                                      echo $formattedPrice; ?>
                                        <input type="checkbox" class="checkboxpreselected precheck-<?php echo $_selection->getId(); ?>" data-dontlike="<?php echo $option->getId(); ?>" id="<?php echo $_selection->getId(); ?>" value="<?php echo $_selection->getId(); ?>" <?php if(/*$_selection->getIsDefault()==1 && */in_array($_selection->getSku(), $allitmesku)) { echo 'checked'; }?>>
                                    </div>
                                  </label>
                                </div>
                              </div>
                            </div>
                           <?php
                    endforeach;
                endforeach;
                ?>
            </div>
            <div class="thelegend mascomposicioneslegend">Otras opciones</div>
            <!--<div class="thelegendbutton">Pulsa aquí</div>-->
            <div class="opcionesDefault mascomposiciones">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <?php foreach ($options as $option): 
                        $titulo=strtolower(str_replace(" ", "", $option->getTitle()));
                    ?>
                        <a class="nav-item nav-link <?php 
                        if($isfirstnav==0){
                            echo " active";
                            $isfirstnav=1;
                        }
                        ?>" id="nav-<?php echo $titulo; ?>-tab" data-toggle="tab" href="#nav-<?php echo $titulo; ?>" role="tab" aria-controls="nav-<?php echo $titulo; ?>" aria-selected="true"><?php echo $option->getTitle(); ?></a>
                    <?php endforeach; ?>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <?php foreach ($options as $option): ?>
                        <?php if (!$option->getSelections()): ?>
                            <?php continue; ?>
                        <?php endif; 
                            $titulo=strtolower(str_replace(" ", "", $option->getTitle()));
                        ?>
                        <div class="tab-pane fade<?php 
                        if($isfirst==0){
                            echo " show active";
                            $isfirst=1;
                        }
                        ?>" id="nav-<?php echo $titulo; ?>" role="tabpanel" aria-labelledby="nav-<?php echo $titulo; ?>-tab">
                            <?= $block->getOptionHtml($option) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?= /* @escapeNotVerified */ __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
